=== Boki0/XML_project/XMLProject/data/A-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:a1="www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo">
    <xs:element name="Autorsko_delo_zahtev">
        <xs:complexType>
            <xs:all>
                <xs:element name="Podnosilac">
                    <xs:complexType>
                        <xs:all>
                            <xs:element minOccurs="0" name="Telefon" nillable="true">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Podaci_podnosioca">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element minOccurs="0" name="Autor" type="TAutor"/>
                                        <xs:element minOccurs="0" name="Punomocnik" nillable="true"
                                            type="TFizicko_lice"/>
                                        <xs:element minOccurs="0" name="Pravno_lice" nillable="true"
                                            type="TPravno_lice"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Autorsko_delo" type="TAutorsko_delo"/>
                <xs:element minOccurs="0" name="Prilog" nillable="true" type="TPrilog"/>
            </xs:all>
            <xs:attribute fixed="ЗАХТЕВ ЗА УНОШЕЊЕ У ЕВИДЕНЦИЈУ И ДЕПОНОВАЊЕ АУТОРСКИХ ДЕЛА"
                name="naslov" type="xs:string"/>
            <xs:attribute name="broj_prijave" type="xs:string"/>
            <xs:attribute name="datum_podnosenja" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPravno_lice">
        <xs:sequence>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element ref="Adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element ref="Adresa"/>
            <xs:element name="Drzavljanstvo" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAutor">
        <xs:complexContent>
            <xs:extension base="TFizicko_lice">
                <xs:sequence>
                    <xs:element minOccurs="0" name="Pseudonim" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Godina_smrti" nillable="true" type="xs:integer"
                    />
                </xs:sequence>
                <xs:attribute name="primarni" type="xs:boolean"/>
                <xs:attribute name="anonimni" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAutori">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Autor" type="TAutor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrilog">
        <xs:all>
            <xs:element name="Sadrzi_opis" type="xs:boolean"/>
            <xs:element name="Sadrzi_primer" type="xs:boolean"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TOsnovno_o_delu">
        <xs:sequence>
            <xs:element name="Identifikator">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="Naslov" type="xs:string"/>
                        <xs:element minOccurs="0" name="Alternativni_naslov" nillable="true"
                            type="xs:string"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="Autori" type="TAutori"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAutorsko_delo">
        <xs:complexContent>
            <xs:extension base="TOsnovno_o_delu">
                <xs:sequence>
                    <xs:element minOccurs="0" name="podaci_o_preradi" nillable="true"
                        type="TOsnovno_o_delu"/>
                    <xs:element minOccurs="0" name="radni_odnos" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="nacin_koriscenja" nillable="true"
                        type="xs:string"/>
                </xs:sequence>
                <xs:attribute name="vrsta" type="xs:string"/>
                <xs:attribute name="forma_zapisa" type="xs:string"/>
                <xs:attribute name="prerada" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== Boki0/XML_project/XMLProject/data/A-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Autorsko_delo_zahtev xmlns:a1="www.ftn.uns.ac.rs/ZahtevZaAutorskoDelo"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/PC/Desktop/kts/XML_project/XMLProject/data/A-1.xsd" naslov="ЗАХТЕВ ЗА УНОШЕЊЕ У ЕВИДЕНЦИЈУ И ДЕПОНОВАЊЕ АУТОРСКИХ ДЕЛА" broj_prijave="BiJCFl0VPyjnw1PFrENN7oe"
     datum_podnosenja="2025-08-15Z">
    <Podnosilac>
        <Telefon>sYpgBA5yvs6QH</Telefon>
        <Email>jAEmo7NQn12</Email>
        <Podaci_podnosioca>
            <Autor primarni="0" anonimni="true">
                <Ime>aOFu8f64</Ime>
                <Prezime>gQux2Q7GztB</Prezime>
                <Adresa>
                    <Mesto>SO4PCS8lw</Mesto>
                    <Ulica>jc27QANBa7</Ulica>
                    <Broj>421720942</Broj>
                </Adresa>
                <Drzavljanstvo>pwb5lCH</Drzavljanstvo>
                <Pseudonim>b-8XRM9BIqC_Ws</Pseudonim>
                <Godina_smrti>570841741</Godina_smrti>
            </Autor>
        </Podaci_podnosioca>
    </Podnosilac>
    <Autorsko_delo vrsta="bPRP" forma_zapisa="VnFPqV.B8QEqn8YITsjmW" prerada="0">
        <Identifikator>
            <Naslov>_eLRZ</Naslov>
            <Alternativni_naslov>qQjQO.</Alternativni_naslov>
        </Identifikator>
        <Autori>
            <Autor primarni="false" anonimni="false">
                <Ime>o052gwY</Ime>
                <Prezime>RE3ZkQ8XA_ldCWTiT6LzKG</Prezime>
                <Adresa>
                    <Mesto>_LRcJqrP</Mesto>
                    <Ulica>KPaqU2bN5axFx9WVdKs</Ulica>
                    <Broj>1289629765</Broj>
                </Adresa>
                <Drzavljanstvo>BeoSS_V2H6PVcoibppfbsd</Drzavljanstvo>
                <Pseudonim>N6</Pseudonim>
                <Godina_smrti>-1322300905</Godina_smrti>
            </Autor>
            <Autor primarni="false" anonimni="false">
                <Ime>zUS1SAkvHEXBUyYylIlVj5wezUKA</Ime>
                <Prezime>Kdsm0EXRBKTND7tQwQstlQOe3f</Prezime>
                <Adresa>
                    <Mesto>wDPcr7y9Gvmuc4hDTCkHf0CCOoPAGoutQGK</Mesto>
                    <Ulica>W3PrvKYywozy8YiJ14m06UdeDEBPIT</Ulica>
                    <Broj>867329605</Broj>
                </Adresa>
                <Drzavljanstvo>UZtogrZEmbtY</Drzavljanstvo>
                <Pseudonim>iLZGjfn2EWhBa-N.dF84c</Pseudonim>
                <Godina_smrti>869392727</Godina_smrti>
            </Autor>
        </Autori>
        <podaci_o_preradi>
            <Identifikator>
                <Naslov>x</Naslov>
                <Alternativni_naslov>xEPGdS2jE99X-JtqK3MQIM0-4mJ</Alternativni_naslov>
            </Identifikator>
            <Autori>
                <Autor primarni="false" anonimni="true">
                    <Ime>DGNrbbegnQFpjgPnTr-0e5K1PXWx_hzch</Ime>
                    <Prezime>GMcrup4.gfqKpyq26</Prezime>
                    <Adresa>
                        <Mesto>Z7txp3N2e7IWgeEB-TsxINw6Y-1FxEaUr3-Zj0fy</Mesto>
                        <Ulica>Kh01AbQ1RbS7z7csma</Ulica>
                        <Broj>1340421746</Broj>
                    </Adresa>
                    <Drzavljanstvo>WPCqmhV</Drzavljanstvo>
                    <Pseudonim>eAYq</Pseudonim>
                    <Godina_smrti>-1579536941</Godina_smrti>
                </Autor>
                <Autor primarni="0" anonimni="false">
                    <Ime>Um6xM3yr-gB4d1vU.x1Dh</Ime>
                    <Prezime>rlgH</Prezime>
                    <Adresa>
                        <Mesto>E2jiPef</Mesto>
                        <Ulica>Vmz5CO_IhRq0E</Ulica>
                        <Broj>1853258194</Broj>
                    </Adresa>
                    <Drzavljanstvo>vrkG0SUcA1yHTQ83VApTNQIYa</Drzavljanstvo>
                    <Pseudonim>kNTehnTDhOiB</Pseudonim>
                    <Godina_smrti>784266071</Godina_smrti>
                </Autor>
            </Autori>
        </podaci_o_preradi>
        <radni_odnos>vh</radni_odnos>
        <nacin_koriscenja>_xi9fioZ</nacin_koriscenja>
    </Autorsko_delo>
    <Prilog>
        <Sadrzi_opis>true</Sadrzi_opis>
        <Sadrzi_primer>true</Sadrzi_primer>
    </Prilog>
</Autorsko_delo_zahtev>
